### ISSUE TITLE
Move out stemcell declararation from deployment-dependencies.yml

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/cf-ops-automation#129]
We support `multi-iaas` config through directory convention (`<root-deployment>/<deployment>/<template>/<iaas-type>`), but `deployment-dependencies.yml` requires `stemcell-name` and `stemcell-version` to be defined into the template. We should move this into `shared-config.yml`, to provide a default value, and customization with `private-config.yml`.

The `shared-config.yml` should look like this:

```
# provides a default value for stemcell to use
default:
  stemcell:
    name:
    # Maybe we should not handle version here, and we should keep it in <xxx>-versions.yml
    version:

# overrides stemcell per root deployment
ops-depls:
  stemcell:
    name:
    # Maybe we should not handle version here, neither
    version:
```
