### ISSUE TITLE
Add support for overriding stemcell and bosh versions

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/cf-ops-automation#15]
For all deployments (manifest file) contained in a BOSH director, the stemcell and bosh versions are defined in the file XXX-depls-versions.yml : 
...
stemcell-version = XXX
bosh-version = YYY
...
The requirement is to enable the overriding capability for a dedicated deployment.

**Comment by poblin-orange** [comment]
as a workaround, for bosh-releases dependency, you could define a dedicated alias in deployment-dependency, which can define a specific version in xxx-depls-versions

deployment-dependencies.yml
```
---
deployment:
  ntp:
    stemcells:
      bosh-openstack-kvm-ubuntu-trusty-go_agent:
    releases:
      ntpv10_boshrelease:
        base_location: https://bosh.io/d/github.com/
        repository: cloudfoundry-community/ntp-release

```

xxx-depls-versions.yml
```
ntp_boshrelease-version: 4
ntpv10_boshrelease-version: 10

```
