### ISSUE TITLE
enable-cf-app.yml does not yet support default values from shared/secrets

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#17]
as a result, we have the following duplicated credentials across apps.

```
cf-app:
  cf-etherpad:
    cf_api_url: 
    cf_username: 
    cf_password: 
    cf_organization: 
    cf_space: 
```

Would be great to have defaults in shared/secrets.yml for these properties
