### ISSUE TITLE
Dump generated manifest on bosh deploy failures

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation#2]
currently a bosh deploy failure only notifies on slack. It would be useful to have the on_failure be invocating multiple steps ([with do ?](https://concourse.ci/do-step.html)), including one that would dump the previously generated manifest

example for admin-ui
```
    - put: deploy-admin-ui
      attempts: 3
      params:
        manifest: final-release-manifest/admin-ui.yml
        stemcells:
        - bosh-stemcell/stemcell.tgz
        releases: 
        
        - admin-ui-boshrelease/release.tgz
        
      on_failure:
        put: failure-alert
        params:
          channel: {{slack-channel}}
          text: Failed to run [[$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME ($BUILD_NAME)]($ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
          icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
          username: Concourse

```
