### ISSUE TITLE
Proposal: untied generation from folder structures

### ISSUE THREAD

**Issue by ArthurHlt** [orange-cloudfoundry/cf-ops-automation#32]
## Introduction

Cf-ops-automation is tied to folder structure which can be a bottleneck for adoption, each teams use is own structure to handle bosh/cf deployment.

This proposal intent also to:
- Have less code to handle deployments (this will remove a lot things did by inspecting structure)
- Be more flexible

## Untied deployment declaration

In this project each deployment must have a `deployment-dependencies.yml` which actually more describe deployment than dependencies.

We can use this file as a more generic solution to describe all deployments and where to find them, this file could be at the root of repository like travis can do with `.travis.yml` or any other CI  system.

Proposal of the new format:
1. Rename this file by `.deployments.yml` and place is in the root folder
2. Deployment declaration could be have a new key called `path` to know where the stubs and templates are for the deployment.
3. Name could be not the first value in the yaml file, key `name` can be added.
4. Remove `enable-cf-app.yml` file, instead prefer use an enum called `type` which can have 2 possible values `bosh` (for bosh deployment) or `cf` for (for cloud foundry app)
5. Add `sites` key which contains list of sites available for deployment (e.g.: `clouwatt`, `openwatt`, `sophia` ...)
6. Add `types` key inside each site declared by `sites` which contains list of type of deployment (e.g.: `prod`, `preprod`, `dev` ...)
7. (*optional*) deployment for cloud foundry app could have multiple cf targets, a `targets` could be added for this usecase.

Here what can look the manifest:
```yml
deployments:
- name: micro-bosh
  type: bosh
  cli_version: v2
  path: path/to/my/deployment
  stemcells:
    bosh-openstack-kvm-ubuntu-trusty-go_agent: latest
  releases:
    route-registrar-boshrelease:
      base_location: https://bosh.io/d/github.com/
      repository: cloudfoundry-community/route-registrar-boshrelease    
    shield:
      base_location: https://bosh.io/d/github.com/
      repository: starkandwayne/shield-boshrelease        
    xxx_boshrelease:
      base_location: https://bosh.io/d/github.com/
      repository: xxx/yyyy
  errands:
    smoke_tests: ~
  sites:
  - name: cloudwatt
    types: [prod, dev]
- name: my-app
  type: bosh
  path: path/to/my/deployment
  targets:
  - cf_api_url: ~
    cf_username: ~
    cf_password: ~
    cf_organization: ~
    cf_space: ~
```

## Use a manifest generation script instead of folder structure in a deployment

Actually, a deployment must always follow a structure and implicit manifest style (like using spruce).

Instead of oblige ops to follow this structure a simple shell script inside the deployment could be called.
Script should always receive the same input from concourse call and always the same output but you ops will be free to construct his final manifest.

Script name should always be called `generate_manifest.sh` to be after used by a CI systems.

As a side benefit by using a script let us be able to deploy in other CI than concourse.

### Script input

```bash
$ ./generate_manifest.sh <sitename> <type>
```

- **Sitename**: define what is the site where we want to deploy. This can be `cloudwatt`, `openwatt`, `sophia`, `bagnolet`...
- **Type**: Define the type of deployment, this can be `prod`, `preprod`, `qa`, `dev`...

Those inputs let ops be able to generate manifest by these identifiers but he is not oblige to use it.
Input will be given by `sites` and `types` keys from `.deployments.yml` file by concourse.

### Script ouput

The output should always return one or many absolute path to manifests to deploy for a deployment.

If there is more than one each path will be separate by a new line:

```bash
$ ./generate_manifest.sh cloudwatt prod
/path/to/my/first/manifest
/path/to/my/second/manifest
```
