### ISSUE TITLE
precompilation should manage per iaas-type bosh release

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#345]
### Expected behavior
As a COA operator, leveraging paas-templates ability to define bosh release per iaas-type, in <root-deployment>/<deployment-xx>/deployment-dependencies-<iaas-type>, i expect bosh releases related to the current iaas-type to be managed in COA 5 precompilation process

### Observed behavior
On COA 5 preview
- given integration environement with iaas-type openstack-hws
- a specific bosh release list in master-depls/bosh-coab/deployment-dependencies-openstack-hws.yml : 

```
---
deployment:
  bosh-coab:
    releases:
      bosh-openstack-cpi:
        base_location: https://bosh.io/d/github.com/
        repository: cloudfoundry/bosh-openstack-cpi-release

```

- master-depls-bosh-precompile-generated does not include the bosh openstack-cpi release
- the bosh-coab concourse job is stuck waiting for the precompiled release:
```
bosh-openstack-cpi - pinned version path:cloudfoundry/bosh-openstack-cpi-41-ubuntu-xenial-621.81.tgz not found
```

### Affected release

Reproduced on version x.y
