### ISSUE TITLE
Include git metadata in bosh manifest

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/cf-ops-automation#381]
**Is your feature request related to a problem? Please describe.**
As an OPS, in order to improve deployment traceability, 

**Describe the solution you'd like**
As bosh deployments may include `tags`, I like below:

bosh manifest sample extract:
```yaml
...
tags:
  coa-templates-commit-author: xxx@example.com
  coa-templates-commit-id: e65a8d4c49d6209301230dfggdfg1181006d8a667cd
  coa-templates-commit-message: |
    Commit from 8fe692b XXXXXXX

```
