### ISSUE TITLE
Allow model sharing across paas-templates

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/cf-ops-automation#63]
Introduces a `shared/models` dir in paas-templates to allow sharing across root deployment.

Origin model could be described in `deployment-dependencies.yml`
```
---
deployment:
  bosh-ops:
    resources:
      template:
        base_path: ["shared/models/bosh"]
      secrets:
...
```

CC: @JCL38-ORANGE
