### ISSUE TITLE
Failed to load root deployment composed only by `disabled` deployment

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/cf-ops-automation#64]
When a root deployment is only composed by `disabled` deployment it cannot be loaded. 

Log output
```
Dependencies loaded: 
---
cf-rabbit:
  status: disabled
mongo-docker:
  status: disabled
cloudfoundry-mysql:
  status: disabled
cf-operator:
  status: disabled
admin-ui:
  status: disabled
```

Error: 
```
exit status 1 - error: invalid configuration:
invalid resources:
	resource 'bosh-stemcell' is not used
```
